<a href="https://colab.research.google.com/github/pranilthorat/almabetter-capstone-project-3-Airline-Passenger-Referral-Prediction-classification-/blob/main/github_commit_for_capstone_project(3)_airline_passenger_refferal_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data includes airline reviews from 2006 to 2019 for popular airlines around the world with
multiple choice and free text questions. Data is scraped in Spring 2019. The main objective
is to predict whether passengers will refer the airline to their friends.

Feature descriptions briefly as follows:

airline: Name of the airline.

overall: Overall point is given to the trip between 1 to 10.

author: Author of the trip

reviewdate: Date of the Review 

customer review: Review of the customers in free text format


aircraft: Type of the aircraft

travellertype: Type of traveler (e.g. business, leisure)

cabin: Cabin at the flight

date flown: Flight date

seat comfort: Rated between 1-5

cabin service: Rated between 1-5

foodbev: Rated between 1-5

entertainment: Rated between 1-5

groundservice: Rated between 1-5

valueformoney: Rated between 1-5

recommended: Binary, target variable.

route= from one location to another location its find by me.

want to study about this for eda and ml model

author: Author of the trip,customer review: Review of the customers in free text format,aircraft: Type of the aircraft,seat comfort: Rated between 1-5, cabin service: Rated between 1-5, foodbev: Rated between 1-5, entertainment: Rated between 1-5, groundservice: Rated between 1-5, valueformoney: Rated between 1-5

In [36]:
# Importing the libraries
import numpy as np
import pandas as pd
from numpy import math

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stat
from scipy import stats
import pylab
from sklearn.linear_model import LogisticRegression
%matplotlib inline

In [37]:
df=pd.read_excel('/content/drive/MyDrive/data_airline_reviews.xlsx')
df.head()

airline  overall  ... value_for_money recommended
0               NaN      NaN  ...             NaN         NaN
1  Turkish Airlines      7.0  ...             4.0         yes
2               NaN      NaN  ...             NaN         NaN
3  Turkish Airlines      2.0  ...             1.0          no
4               NaN      NaN  ...             NaN         NaN

[5 rows x 17 columns]

In [38]:
df.shape

(131895, 17)

In [39]:
df.describe()

overall  seat_comfort  ...  ground_service  value_for_money
count  64017.000000  60681.000000  ...    39358.000000     63975.000000
mean       5.145430      2.952160  ...        2.692820         2.943962
std        3.477532      1.441362  ...        1.612215         1.587370
min        1.000000      1.000000  ...        1.000000         1.000000
25%        1.000000      1.000000  ...        1.000000         1.000000
50%        5.000000      3.000000  ...        3.000000         3.000000
75%        9.000000      4.000000  ...        4.000000         4.000000
max       10.000000      5.000000  ...        5.000000         5.000000

[8 rows x 7 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131895 entries, 0 to 131894
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   airline          65947 non-null  object 
 1   overall          64017 non-null  float64
 2   author           65947 non-null  object 
 3   review_date      65947 non-null  object 
 4   customer_review  65947 non-null  object 
 5   aircraft         19718 non-null  object 
 6   traveller_type   39755 non-null  object 
 7   cabin            63303 non-null  object 
 8   route            39726 non-null  object 
 9   date_flown       39633 non-null  object 
 10  seat_comfort     60681 non-null  float64
 11  cabin_service    60715 non-null  float64
 12  food_bev         52608 non-null  float64
 13  entertainment    44193 non-null  float64
 14  ground_service   39358 non-null  float64
 15  value_for_money  63975 non-null  float64
 16  recommended      64440 non-null  object 
dtypes: float64

In [41]:
df.isnull().sum()

airline             65948
overall             67878
author              65948
review_date         65948
customer_review     65948
aircraft           112177
traveller_type      92140
cabin               68592
route               92169
date_flown          92262
seat_comfort        71214
cabin_service       71180
food_bev            79287
entertainment       87702
ground_service      92537
value_for_money     67920
recommended         67455
dtype: int64

In [42]:
df['airline'].value_counts()

Spirit Airlines           2934
American Airlines         2867
United Airlines           2829
British Airways           2811
Cathay Pacific Airways    2402
                          ... 
QantasLink                 105
Adria Airways               85
Air Arabia                  80
Tunisair                    71
Thai Smile Airways          48
Name: airline, Length: 81, dtype: int64

# droping unneccesary columns

In [43]:
df.columns

Index(['airline', 'overall', 'author', 'review_date', 'customer_review',
       'aircraft', 'traveller_type', 'cabin', 'route', 'date_flown',
       'seat_comfort', 'cabin_service', 'food_bev', 'entertainment',
       'ground_service', 'value_for_money', 'recommended'],
      dtype='object')

In [44]:
airline_df=df.drop(['airline','author','review_date','aircraft','route','date_flown','customer_review'],axis = 1)
airline_df.head()

overall  traveller_type  ... value_for_money  recommended
0      NaN             NaN  ...             NaN          NaN
1      7.0        Business  ...             4.0          yes
2      NaN             NaN  ...             NaN          NaN
3      2.0  Family Leisure  ...             1.0           no
4      NaN             NaN  ...             NaN          NaN

[5 rows x 10 columns]

In [45]:
airline_df['recommended'].value_counts()

no     33894
yes    30546
Name: recommended, dtype: int64

In [46]:
df_2=airline_df.dropna(subset=['recommended'])

In [47]:
df_2.head()

overall  traveller_type  ... value_for_money  recommended
1      7.0        Business  ...             4.0          yes
3      2.0  Family Leisure  ...             1.0           no
5      3.0        Business  ...             2.0           no
7     10.0    Solo Leisure  ...             5.0          yes
9      1.0    Solo Leisure  ...             1.0           no

[5 rows x 10 columns]

In [48]:
df_2['recommended'].unique()

array(['yes', 'no'], dtype=object)

In [49]:
df_2.shape

(64440, 10)

In [50]:
print(df_2.isnull().sum().sort_values(ascending = False))
print(df_2.isnull().sum().sort_values(ascending = False)/len(df_2)*100)

ground_service     25082
traveller_type     24686
entertainment      20247
food_bev           11832
seat_comfort        3759
cabin_service       3725
overall             1910
cabin               1138
value_for_money      465
recommended            0
dtype: int64
ground_service     38.923029
traveller_type     38.308504
entertainment      31.419926
food_bev           18.361266
seat_comfort        5.833333
cabin_service       5.780571
overall             2.963998
cabin               1.765984
value_for_money     0.721601
recommended         0.000000
dtype: float64


In [51]:
df_2['cabin'].value_counts()

Economy Class      48557
Business Class     10326
Premium Economy     2799
First Class         1620
Name: cabin, dtype: int64

In [52]:
df_2['traveller_type'].value_counts()

Solo Leisure      14797
Couple Leisure    10285
Family Leisure     7583
Business           7089
Name: traveller_type, dtype: int64

In [53]:
10285/(14797+10285+7583+7089)

0.2587161040398451

In [54]:
df_3=df_2.groupby(['traveller_type','cabin'])
df_3.head()

overall  traveller_type  ... value_for_money  recommended
1          7.0        Business  ...             4.0          yes
3          2.0  Family Leisure  ...             1.0           no
5          3.0        Business  ...             2.0           no
7         10.0    Solo Leisure  ...             5.0          yes
9          1.0    Solo Leisure  ...             1.0           no
...        ...             ...  ...             ...          ...
9761       2.0    Solo Leisure  ...             1.0           no
9785       7.0  Family Leisure  ...             4.0           no
9873       1.0    Solo Leisure  ...             1.0           no
10131      2.0  Family Leisure  ...             1.0           no
10657     10.0  Family Leisure  ...             5.0          yes

[85 rows x 10 columns]

In [55]:
df_3['traveller_type'].value_counts()

traveller_type  cabin            traveller_type
Business        Business Class   Business           2025
                Economy Class    Business           4406
                First Class      Business            269
                Premium Economy  Business            385
Couple Leisure  Business Class   Couple Leisure     1459
                Economy Class    Couple Leisure     8118
                First Class      Couple Leisure      206
                Premium Economy  Couple Leisure      495
Family Leisure  Business Class   Family Leisure      576
                Economy Class    Family Leisure     6641
                First Class      Family Leisure      144
                Premium Economy  Family Leisure      221
Solo Leisure    Business Class   Solo Leisure       1910
                Economy Class    Solo Leisure      12004
                First Class      Solo Leisure        333
                Premium Economy  Solo Leisure        542
Name: traveller_type, dtype: int64

In [56]:
df_3.size()

traveller_type  cabin          
Business        Business Class      2025
                Economy Class       4406
                First Class          269
                Premium Economy      385
Couple Leisure  Business Class      1459
                Economy Class       8118
                First Class          206
                Premium Economy      495
Family Leisure  Business Class       576
                Economy Class       6641
                First Class          144
                Premium Economy      221
Solo Leisure    Business Class      1910
                Economy Class      12004
                First Class          333
                Premium Economy      542
dtype: int64

**so now we need to do one assumpton that is=**

1] in cabin column 1.76% values are null and if we see in that column there are many more than 75% are from economy class so we will fill null values in that column as an economy class.

2] in traveller type Solo Leisure has more than 37% and Couple Leisure has more than 25% value so we will fill this into that colunm

In [57]:
df_2['cabin'].fillna('Economy Class',inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [58]:
df_2['traveller_type'].fillna(method="ffill",inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [59]:
df_2['traveller_type'].value_counts()

Solo Leisure      26182
Couple Leisure    17081
Business          10743
Family Leisure    10434
Name: traveller_type, dtype: int64

In [60]:
10434/len(df_2)

0.16191806331471137

In [61]:
df_2['entertainment'].unique()

array([ 4.,  1.,  3.,  5., nan,  2.])

In [62]:
df_2['overall'].unique()

array([ 7.,  2.,  3., 10.,  1.,  6.,  8.,  5.,  4.,  9., nan])

In [63]:
df_2['seat_comfort'].unique()

array([ 4.,  1.,  3.,  2.,  5., nan])

In [64]:
df_2['cabin_service'].unique()

array([ 5.,  1.,  4.,  3.,  2., nan])

In [65]:
df_2['food_bev'].unique()

array([ 4.,  1.,  5., nan,  2.,  3.])

In [66]:
df_2['ground_service'].unique()

array([ 2.,  1.,  5.,  3.,  4., nan])

In [67]:
df_2['value_for_money'].unique()

array([ 4.,  1.,  2.,  5.,  3., nan])

In [68]:
df_2.columns

Index(['overall', 'traveller_type', 'cabin', 'seat_comfort', 'cabin_service',
       'food_bev', 'entertainment', 'ground_service', 'value_for_money',
       'recommended'],
      dtype='object')

In [69]:
# filling null values of all numerical feature by median 
df_2['overall'].fillna(df_2['overall'].median(),inplace=True)
df_2['seat_comfort'].fillna(df_2['seat_comfort'].median(),inplace=True)
df_2['cabin_service'].fillna(df_2['cabin_service'].median(),inplace=True)
df_2['food_bev'].fillna(df_2['food_bev'].median(),inplace=True)
df_2['entertainment'].fillna(df_2['entertainment'].median(),inplace=True)
df_2['ground_service'].fillna(df_2['ground_service'].median(),inplace=True)
df_2['value_for_money'].fillna(df_2['value_for_money'].median(),inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [70]:
df_2.isnull().sum()

overall            0
traveller_type     0
cabin              0
seat_comfort       0
cabin_service      0
food_bev           0
entertainment      0
ground_service     0
value_for_money    0
recommended        0
dtype: int64

In [71]:
df_2.head()

overall  traveller_type  ... value_for_money  recommended
1      7.0        Business  ...             4.0          yes
3      2.0  Family Leisure  ...             1.0           no
5      3.0        Business  ...             2.0           no
7     10.0    Solo Leisure  ...             5.0          yes
9      1.0    Solo Leisure  ...             1.0           no

[5 rows x 10 columns]

In [72]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64440 entries, 1 to 131894
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   overall          64440 non-null  float64
 1   traveller_type   64440 non-null  object 
 2   cabin            64440 non-null  object 
 3   seat_comfort     64440 non-null  float64
 4   cabin_service    64440 non-null  float64
 5   food_bev         64440 non-null  float64
 6   entertainment    64440 non-null  float64
 7   ground_service   64440 non-null  float64
 8   value_for_money  64440 non-null  float64
 9   recommended      64440 non-null  object 
dtypes: float64(7), object(3)
memory usage: 5.4+ MB


In [73]:
#Converting column traveller_type into dummy variables
traveller_type =pd.get_dummies(df_2['traveller_type'],drop_first=True)

In [74]:
df_2=pd.concat([df_2,traveller_type],axis='columns')

In [75]:
cabin =pd.get_dummies(df_2['cabin'],drop_first=True)

In [76]:
df_2=pd.concat([df_2,cabin],axis='columns')

In [77]:
df_2.drop(['traveller_type','cabin'],axis=1,inplace=True)

In [78]:
df_2.head()

overall  seat_comfort  ...  First Class  Premium Economy
1      7.0           4.0  ...            0                0
3      2.0           4.0  ...            0                0
5      3.0           1.0  ...            0                0
7     10.0           4.0  ...            0                0
9      1.0           1.0  ...            0                0

[5 rows x 14 columns]

In [79]:
#Creating a copy of our dataframe
data=df_2.copy()

In [80]:
data.head()

overall  seat_comfort  ...  First Class  Premium Economy
1      7.0           4.0  ...            0                0
3      2.0           4.0  ...            0                0
5      3.0           1.0  ...            0                0
7     10.0           4.0  ...            0                0
9      1.0           1.0  ...            0                0

[5 rows x 14 columns]

In [81]:
dependent_variable = 'recommended'

In [82]:
# Create a list of independent variables
independent_variables = list(set(data.columns.tolist()) - {dependent_variable})

In [83]:
independent_variables

['Economy Class',
 'Premium Economy',
 'seat_comfort',
 'Solo Leisure',
 'value_for_money',
 'entertainment',
 'ground_service',
 'First Class',
 'Family Leisure',
 'overall',
 'cabin_service',
 'Couple Leisure',
 'food_bev']

In [84]:
# Create the data of independent variables
X = data[independent_variables].values

# Create the dependent variable data
y = data[dependent_variable].values

In [85]:
data[independent_variables]

Economy Class  Premium Economy  ...  Couple Leisure  food_bev
1                   1                0  ...               0       4.0
3                   1                0  ...               0       1.0
5                   1                0  ...               0       1.0
7                   1                0  ...               0       5.0
9                   1                0  ...               0       1.0
...               ...              ...  ...             ...       ...
131886              1                0  ...               1       3.0
131888              1                0  ...               1       3.0
131890              1                0  ...               1       3.0
131892              1                0  ...               1       3.0
131894              1                0  ...               1       3.0

[64440 rows x 13 columns]

In [86]:
X_train, X_test, y_train, y_test = train_test_split( X,y , test_size = 0.2, random_state = 0) 
print(X_train.shape)
print(X_test.shape)

(51552, 13)
(12888, 13)


# Fitting logistic regression on train data

In [87]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(fit_intercept=True, max_iter=10000)
clf.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [88]:
clf.coef_

array([[-0.05357252, -0.14151322,  0.17717964, -0.05507664,  0.86986761,
         0.12154986,  0.22946467, -0.1513243 , -0.1020467 ,  1.00463864,
         0.37170976, -0.22997516,  0.15034094]])

In [89]:
clf.intercept_

array([-11.29145977])

# Evaluating the performance of the trained model

In [90]:
# Get the predicted probabilities
train_preds = clf.predict_proba(X_train)
test_preds = clf.predict_proba(X_test)

In [91]:
test_preds

array([[9.99723031e-01, 2.76969268e-04],
       [9.99398596e-01, 6.01403712e-04],
       [9.99570259e-01, 4.29740509e-04],
       ...,
       [9.99698511e-01, 3.01489227e-04],
       [5.37045351e-03, 9.94629546e-01],
       [9.90521607e-01, 9.47839289e-03]])

In [92]:
# Get the predicted classes
train_class_preds = clf.predict(X_train)
test_class_preds = clf.predict(X_test)

In [93]:
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns

In [94]:
# Get the accuracy scores
train_accuracy = accuracy_score(train_class_preds,y_train)
test_accuracy = accuracy_score(test_class_preds,y_test)

print("The accuracy on train data is ", train_accuracy)
print("The accuracy on test data is ", test_accuracy)

The accuracy on train data is  0.9583721291123526
The accuracy on test data is  0.9568590937306021
